name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  test:
    uses: survos/.github/.github/workflows/php-test-symfony.yml@main

#  code-coverage:
#    uses: survos/.github/.github/workflows/php-coverage-codecov.yml@main

  composer-validate:
    uses: survos/.github/.github/workflows/php-composer-validate.yml@main

#  sca:
#    uses: survos/.github/.github/workflows/php-stan.yml@main

#  fixcs:
#    name: Run php-cs-fixer
#    needs: sync-with-template
#    if: (github.event_name == 'push' || github.event_name == 'schedule') && !startsWith(github.ref, 'refs/tags')
#    runs-on: ubuntu-latest
#    steps:
#      - uses: survos/.github@php-cs-fixer
#        with:
#          php: 8
#          key: ${{ secrets.GPG_PRIVATE_KEY }}
#          token: ${{ secrets.COMPOSER_TOKEN }}
#
#  sync-with-template:
#    name: Sync meta files
#    if: (github.event_name == 'push' || github.event_name == 'schedule') && !startsWith(github.ref, 'refs/tags')
#    runs-on: ubuntu-latest
#    steps:
#      - uses: survos/.github@sync-with-template
#        with:
#          key: ${{ secrets.GPG_PRIVATE_KEY }}
#          token: ${{ secrets.COMPOSER_TOKEN }}
